/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.lista04;

/**
 *
 * @author andre
 */
public class Lutadores extends javax.swing.JFrame {
    
    Lutador lutador1 = new Lutador();
    Lutador lutador2 = new Lutador();

    /**
     * Creates new form Lutadores
     */
    public Lutadores() {
        initComponents();
    }
   
    void bloqueaBotoes() {
        btnApanhar1.setEnabled(false);
        btnApanhar2.setEnabled(false);
        btnConcentrar1.setEnabled(false);
        btnConcentrar2.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblResultado = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pgbLutador2 = new javax.swing.JProgressBar();
        pgbLutador1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnConcentrar1 = new javax.swing.JButton();
        btnApanhar1 = new javax.swing.JButton();
        btnApanhar2 = new javax.swing.JButton();
        btnConcentrar2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblResultado.setText("-");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("UFC JAVA");

        pgbLutador2.setValue(100);

        pgbLutador1.setValue(100);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Lutador 1:");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Lutador 2:");

        btnConcentrar1.setText("Concentrar força");
        btnConcentrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConcentrar1ActionPerformed(evt);
            }
        });

        btnApanhar1.setText("Apanhar");
        btnApanhar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApanhar1ActionPerformed(evt);
            }
        });

        btnApanhar2.setText("Apanhar");
        btnApanhar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApanhar2ActionPerformed(evt);
            }
        });

        btnConcentrar2.setText("Concentrar força");
        btnConcentrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConcentrar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnApanhar2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnConcentrar2))
                            .addComponent(pgbLutador1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                            .addComponent(pgbLutador2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnApanhar1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnConcentrar1))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel3)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pgbLutador1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConcentrar1)
                    .addComponent(btnApanhar1))
                .addGap(51, 51, 51)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pgbLutador2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConcentrar2)
                    .addComponent(btnApanhar2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblResultado)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConcentrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConcentrar1ActionPerformed
        lutador1.concentrarForca();
        pgbLutador1.setValue(lutador1.getVida());
        pgbLutador1.setStringPainted(true);
        pgbLutador1.setString(lutador1.getVida().toString());
    }//GEN-LAST:event_btnConcentrar1ActionPerformed

    private void btnApanhar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApanhar1ActionPerformed
        if (lutador1.getVida() <= 0) {
            lblResultado.setText("1 perdeu");
            bloqueaBotoes();
        } else {
            lutador1.apanhar();
            pgbLutador1.setValue(lutador1.getVida());
            pgbLutador1.setStringPainted(true);
            pgbLutador1.setString(lutador1.getVida().toString());
        }
    }//GEN-LAST:event_btnApanhar1ActionPerformed

    private void btnApanhar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApanhar2ActionPerformed
        if (lutador2.getVida() <= 0) {
            lblResultado.setText("2 perdeu");
            bloqueaBotoes();
        } else {
            lutador2.apanhar();
            pgbLutador2.setValue(lutador2.getVida());
            pgbLutador2.setStringPainted(true);
            pgbLutador2.setString(lutador2.getVida().toString());
        }
    }//GEN-LAST:event_btnApanhar2ActionPerformed

    private void btnConcentrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConcentrar2ActionPerformed
        lutador2.concentrarForca();
        pgbLutador2.setValue(lutador2.getVida());
        pgbLutador2.setStringPainted(true);
        pgbLutador2.setString(lutador2.getVida().toString());
    }//GEN-LAST:event_btnConcentrar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lutadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lutadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lutadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lutadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lutadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApanhar1;
    private javax.swing.JButton btnApanhar2;
    private javax.swing.JButton btnConcentrar1;
    private javax.swing.JButton btnConcentrar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JProgressBar pgbLutador1;
    private javax.swing.JProgressBar pgbLutador2;
    // End of variables declaration//GEN-END:variables
}
